### ISSUE TITLE
The readme uses newer version than supported 

### ISSUE THREAD

**Issue by ProAdmin007** [robertdebock/terraform-action#1]
Hi, Your readme insists on using version 1.1.3 but I get a error when I run the .yml file because 1.1.3 does not exists.
I used 1.1.2 and that works for me.

```
---
on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: terraform
        uses: robertdebock/terraform-action@1.1.3
```
